work1 = [
"Salvador de",
"Protector de",
"Defensor de",
"Vigilante de",
"Luchador contra",
"Capitán de",
"Jefe de la misión de",
"Entrenador de",
"Combatiente contra",
"Guardián de",
"Líder de",
"Jefe de la misión para",
"Líder de la lucha contra",
"Defensor de los derechos de",
"Jefe de la misión para salvar a",
]

work2 = [
" los gatos en árboles",
"los sugar daddys",
" los derechos de los unicornios",
" la justicia en la lucha contra el aburrimiento",
"las viejitas pensionadas",
" las mujeres que aman el colageno",
" rescate de gente atrapada en laberintos",
" la tanga en los hombres",
" la maldición de la muerte del payaso",
" la clave para entender a las mujeres",
" la expedición para encontrar mujeres sin bendicion",
"la liberacion de los rehenes de los villanos",
"evitar que un hombre mienta",
" salvar al mundo de la destrucción",
" la invasión de las mujeres fieles",
"el demonio de mi cuarto",
" detener a las mujeres que tienen mas de un novio",
" la deteccion de los hombres fieles",
" salvar a los prisioneros de las garras del mal",
" la invasión de los zombis",
" el crecimiento de las bubbys",
" encontrar la fuente de la eterna juventud",
" la amenaza de la invasión de bendiciones",
" encontrar la ciudad perdida de las amazonas",
" la amenaza de los robots asesinos",
" resistir la tentacion",
"el hallazgo de viejitas pensionadas proximas a morir",
" la amenaza de la oscuridad en el multiverso",
" salvar al mundo de los hombres que tienen ojos para varias",
" la invasión de las virgenes",
" encontrar mujeres fieles",
" la amenaza de la invasión de los fantasmas",
" salvar a las mujeres de los hombres mentirosos",
" las chicas webcam",
" los chicos webcam",
"las mujeres facturando en onlyfans",
"los hombres facturando en onlyfans",
]